### ISSUE TITLE
跑不起来，不知道缺什么东西

### ISSUE THREAD

**Issue by Kojima648** [JingyibySUTsoftware/Yolov5-deepsort-driverDistracted-driving-behavior-detection#11]
Fusing layers... 
Model Summary: 224 layers, 7062001 parameters, 0 gradients
Traceback (most recent call last):
  File "d:\Downloads\Yolov5-deepsort-driverDistracted-driving-behavior-detection\main.py", line 11, in <module>
    import myframe
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "d:\Downloads\Yolov5-deepsort-driverDistracted-driving-behavior-detection\myframe.py", line 5, in <module>
    import myfatigue    #疲劳检测
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "d:\Downloads\Yolov5-deepsort-driverDistracted-driving-behavior-detection\myfatigue.py", line 4, in <module>
    from imutils.video import FileVideoStream
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'imutils'
PS D:\Downloads\Yolov5-deepsort-driverDistracted-driving-behavior-detection>

**Comment by Bright-MoonBeam** [comment]
我也是这个问题，兄弟解决了吗？

**Comment by Kojima648** [comment]
> 我也是这个问题，兄弟解决了吗？

没解决，换别的方案了。

**Comment by milisl** [comment]
要下载一个imutils库啊

**Comment by xzp12345** [comment]
Traceback (most recent call last):
  File "E:\Pycharm\Project\pythonProject2\Project\Yolov5-deepsort-driverDistracted-driving-behavior-detection-1.0\main.py", line 11, in <module>
    import myframe
  File "E:\Anacondaaddress\envs\yolo\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "E:\Pycharm\Project\pythonProject2\Project\Yolov5-deepsort-driverDistracted-driving-behavior-detection-1.0\myframe.py", line 4, in <module>
    import mydetect     #yolo检测
  File "E:\Anacondaaddress\envs\yolo\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "E:\Pycharm\Project\pythonProject2\Project\Yolov5-deepsort-driverDistracted-driving-behavior-detection-1.0\mydetect.py", line 9, in <module>
    from models.experimental import attempt_load
  File "E:\Anacondaaddress\envs\yolo\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "E:\Pycharm\Project\pythonProject2\Project\Yolov5-deepsort-driverDistracted-driving-behavior-detection-1.0\models\experimental.py", line 7, in <module>
    from models.common import Conv, DWConv
  File "E:\Anacondaaddress\envs\yolo\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "E:\Pycharm\Project\pythonProject2\Project\Yolov5-deepsort-driverDistracted-driving-behavior-detection-1.0\models\common.py", line 11, in <module>
    from utils.datasets import letterbox
  File "E:\Anacondaaddress\envs\yolo\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "E:\Pycharm\Project\pythonProject2\Project\Yolov5-deepsort-driverDistracted-driving-behavior-detection-1.0\utils\datasets.py", line 21, in <module>
    from tqdm import tqdm
  File "E:\Anacondaaddress\envs\yolo\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'tqdm'
这个问题是少了什么库吗？
